# Generated by Django 5.2.8 on 2026-04-21 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0002_panchayat_alter_ward_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='wards.panchayat'),
        ),
    ]
