# Generated by Django 6.0.3 on 2026-03-21 06:22

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/images/', validators=[complaints.models.Complaint.validate_image_size]),
        ),
    ]
