# Generated by Django 5.2.8 on 2026-04-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='issue_category',
            field=models.CharField(max_length=150),
        ),
    ]
